### ISSUE TITLE
Twitch says "file is too large"

### ISSUE THREAD

**Issue by flleeppyy** [tma02/twitch-emote-resizer#1]
Perhaps add image compression for files that are larger than what twitch allows.
Twitch only allows 25kb, and my 112x112 one was larger than 25kb

![image](https://user-images.githubusercontent.com/18307183/112745142-21651280-8f5b-11eb-86e8-4c1c6f921293.png)
![image](https://user-images.githubusercontent.com/18307183/112745153-304bc500-8f5b-11eb-806e-d1cd25daac63.png)

**Comment by tma02** [comment]
Thanks, this was not something I had considered. Compression via quantization is now built-in with 6b665ab.
