### ISSUE TITLE
New compression feature bug

### ISSUE THREAD

**Issue by noremori** [tma02/twitch-emote-resizer#2]
Hello, I am a big fan of this emote resizer and had used this website frequently, but the new compression feature somehow made the resized emote have some white holes in them

![image](https://user-images.githubusercontent.com/81573673/112849451-47152780-90d3-11eb-941d-c86a3b75192d.png)
^the new compressed emotes

![image](https://user-images.githubusercontent.com/81573673/112849810-9d826600-90d3-11eb-96f8-c0f28a68011f.png)
^the old emotes i used with this website a few weeks ago

**Comment by noremori** [comment]
oh right, i think the only ones that had problem is the 112px ones

**Comment by tma02** [comment]
Would you be willing to share just the source image you're trying to resize?

**Comment by noremori** [comment]
> Would you be willing to share just the source image you're trying to resize?

alright here you go
![sip](https://user-images.githubusercontent.com/81573673/112906698-cb3cce80-9116-11eb-87c0-77f2ca52c16d.png)


![image](https://user-images.githubusercontent.com/81573673/112906763-ee677e00-9116-11eb-811a-e9ea69e65d7d.png)
i tried to resized an emote i've resized before the compression update and you can really see the differences

**Comment by flleeppyy** [comment]
I could try to figure this out
ill just mess with numbers until it works

**Comment by tma02** [comment]
Should be fixed in fa3470d, at least for that sample image. Please reopen if this is there are still issues.
